//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blk.Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blk.Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ACPpow_16 {
            get {
                object obj = ResourceManager.GetObject("ACPpow_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ACPpow_24 {
            get {
                object obj = ResourceManager.GetObject("ACPpow_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ACPpow_32 {
            get {
                object obj = ResourceManager.GetObject("ACPpow_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ACPpow_48 {
            get {
                object obj = ResourceManager.GetObject("ACPpow_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Add_16 {
            get {
                object obj = ResourceManager.GetObject("Add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Add_24 {
            get {
                object obj = ResourceManager.GetObject("Add_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Add_32 {
            get {
                object obj = ResourceManager.GetObject("Add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Add_48 {
            get {
                object obj = ResourceManager.GetObject("Add_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowNext_16 {
            get {
                object obj = ResourceManager.GetObject("ArrowNext_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowNext_24 {
            get {
                object obj = ResourceManager.GetObject("ArrowNext_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowNext_32 {
            get {
                object obj = ResourceManager.GetObject("ArrowNext_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowNext_48 {
            get {
                object obj = ResourceManager.GetObject("ArrowNext_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr000_16 {
            get {
                object obj = ResourceManager.GetObject("BatChr000_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr000_24 {
            get {
                object obj = ResourceManager.GetObject("BatChr000_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr000_32 {
            get {
                object obj = ResourceManager.GetObject("BatChr000_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr000_48 {
            get {
                object obj = ResourceManager.GetObject("BatChr000_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr020_16 {
            get {
                object obj = ResourceManager.GetObject("BatChr020_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr020_24 {
            get {
                object obj = ResourceManager.GetObject("BatChr020_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr020_32 {
            get {
                object obj = ResourceManager.GetObject("BatChr020_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr020_48 {
            get {
                object obj = ResourceManager.GetObject("BatChr020_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr040_16 {
            get {
                object obj = ResourceManager.GetObject("BatChr040_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr040_24 {
            get {
                object obj = ResourceManager.GetObject("BatChr040_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr040_32 {
            get {
                object obj = ResourceManager.GetObject("BatChr040_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr040_48 {
            get {
                object obj = ResourceManager.GetObject("BatChr040_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr060_16 {
            get {
                object obj = ResourceManager.GetObject("BatChr060_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr060_24 {
            get {
                object obj = ResourceManager.GetObject("BatChr060_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr060_32 {
            get {
                object obj = ResourceManager.GetObject("BatChr060_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr060_48 {
            get {
                object obj = ResourceManager.GetObject("BatChr060_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr080_16 {
            get {
                object obj = ResourceManager.GetObject("BatChr080_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr080_24 {
            get {
                object obj = ResourceManager.GetObject("BatChr080_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr080_32 {
            get {
                object obj = ResourceManager.GetObject("BatChr080_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr080_48 {
            get {
                object obj = ResourceManager.GetObject("BatChr080_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr100_16 {
            get {
                object obj = ResourceManager.GetObject("BatChr100_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr100_24 {
            get {
                object obj = ResourceManager.GetObject("BatChr100_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr100_32 {
            get {
                object obj = ResourceManager.GetObject("BatChr100_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatChr100_48 {
            get {
                object obj = ResourceManager.GetObject("BatChr100_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis000_16 {
            get {
                object obj = ResourceManager.GetObject("BatDis000_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis000_24 {
            get {
                object obj = ResourceManager.GetObject("BatDis000_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis000_32 {
            get {
                object obj = ResourceManager.GetObject("BatDis000_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis000_48 {
            get {
                object obj = ResourceManager.GetObject("BatDis000_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis020_16 {
            get {
                object obj = ResourceManager.GetObject("BatDis020_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis020_24 {
            get {
                object obj = ResourceManager.GetObject("BatDis020_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis020_32 {
            get {
                object obj = ResourceManager.GetObject("BatDis020_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis020_48 {
            get {
                object obj = ResourceManager.GetObject("BatDis020_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis040_16 {
            get {
                object obj = ResourceManager.GetObject("BatDis040_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis040_24 {
            get {
                object obj = ResourceManager.GetObject("BatDis040_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis040_32 {
            get {
                object obj = ResourceManager.GetObject("BatDis040_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis040_48 {
            get {
                object obj = ResourceManager.GetObject("BatDis040_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis060_16 {
            get {
                object obj = ResourceManager.GetObject("BatDis060_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis060_24 {
            get {
                object obj = ResourceManager.GetObject("BatDis060_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis060_32 {
            get {
                object obj = ResourceManager.GetObject("BatDis060_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis060_48 {
            get {
                object obj = ResourceManager.GetObject("BatDis060_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis080_16 {
            get {
                object obj = ResourceManager.GetObject("BatDis080_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis080_24 {
            get {
                object obj = ResourceManager.GetObject("BatDis080_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis080_32 {
            get {
                object obj = ResourceManager.GetObject("BatDis080_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis080_48 {
            get {
                object obj = ResourceManager.GetObject("BatDis080_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis100_16 {
            get {
                object obj = ResourceManager.GetObject("BatDis100_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis100_24 {
            get {
                object obj = ResourceManager.GetObject("BatDis100_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis100_32 {
            get {
                object obj = ResourceManager.GetObject("BatDis100_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatDis100_48 {
            get {
                object obj = ResourceManager.GetObject("BatDis100_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatUnknown_16 {
            get {
                object obj = ResourceManager.GetObject("BatUnknown_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatUnknown_24 {
            get {
                object obj = ResourceManager.GetObject("BatUnknown_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatUnknown_32 {
            get {
                object obj = ResourceManager.GetObject("BatUnknown_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatUnknown_48 {
            get {
                object obj = ResourceManager.GetObject("BatUnknown_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap busy16 {
            get {
                object obj = ResourceManager.GetObject("busy16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap busy24 {
            get {
                object obj = ResourceManager.GetObject("busy24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap busy32 {
            get {
                object obj = ResourceManager.GetObject("busy32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap busy48 {
            get {
                object obj = ResourceManager.GetObject("busy48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleBlue_16 {
            get {
                object obj = ResourceManager.GetObject("CircleBlue_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleBlue_24 {
            get {
                object obj = ResourceManager.GetObject("CircleBlue_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleBlue_32 {
            get {
                object obj = ResourceManager.GetObject("CircleBlue_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleBlue_48 {
            get {
                object obj = ResourceManager.GetObject("CircleBlue_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleGray_16 {
            get {
                object obj = ResourceManager.GetObject("CircleGray_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleGray_24 {
            get {
                object obj = ResourceManager.GetObject("CircleGray_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleGray_32 {
            get {
                object obj = ResourceManager.GetObject("CircleGray_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleGray_48 {
            get {
                object obj = ResourceManager.GetObject("CircleGray_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleGreen_16 {
            get {
                object obj = ResourceManager.GetObject("CircleGreen_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleGreen_24 {
            get {
                object obj = ResourceManager.GetObject("CircleGreen_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleGreen_32 {
            get {
                object obj = ResourceManager.GetObject("CircleGreen_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleGreen_48 {
            get {
                object obj = ResourceManager.GetObject("CircleGreen_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleOrange_16 {
            get {
                object obj = ResourceManager.GetObject("CircleOrange_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleOrange_24 {
            get {
                object obj = ResourceManager.GetObject("CircleOrange_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleOrange_32 {
            get {
                object obj = ResourceManager.GetObject("CircleOrange_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleOrange_48 {
            get {
                object obj = ResourceManager.GetObject("CircleOrange_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap err16 {
            get {
                object obj = ResourceManager.GetObject("err16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap err24 {
            get {
                object obj = ResourceManager.GetObject("err24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap err32 {
            get {
                object obj = ResourceManager.GetObject("err32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap err48 {
            get {
                object obj = ResourceManager.GetObject("err48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExitGreen_16 {
            get {
                object obj = ResourceManager.GetObject("ExitGreen_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExitGreen_24 {
            get {
                object obj = ResourceManager.GetObject("ExitGreen_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExitGreen_32 {
            get {
                object obj = ResourceManager.GetObject("ExitGreen_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExitGreen_48 {
            get {
                object obj = ResourceManager.GetObject("ExitGreen_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExitRed_16 {
            get {
                object obj = ResourceManager.GetObject("ExitRed_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExitRed_24 {
            get {
                object obj = ResourceManager.GetObject("ExitRed_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExitRed_32 {
            get {
                object obj = ResourceManager.GetObject("ExitRed_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExitRed_48 {
            get {
                object obj = ResourceManager.GetObject("ExitRed_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Filter2HS {
            get {
                object obj = ResourceManager.GetObject("Filter2HS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gear16 {
            get {
                object obj = ResourceManager.GetObject("Gear16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gear24 {
            get {
                object obj = ResourceManager.GetObject("Gear24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gear32 {
            get {
                object obj = ResourceManager.GetObject("Gear32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InjectBlue_16 {
            get {
                object obj = ResourceManager.GetObject("InjectBlue_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InjectBlue_24 {
            get {
                object obj = ResourceManager.GetObject("InjectBlue_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InjectBlue_32 {
            get {
                object obj = ResourceManager.GetObject("InjectBlue_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InjectBlue_48 {
            get {
                object obj = ResourceManager.GetObject("InjectBlue_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InjectGreen_16 {
            get {
                object obj = ResourceManager.GetObject("InjectGreen_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InjectGreen_24 {
            get {
                object obj = ResourceManager.GetObject("InjectGreen_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InjectGreen_32 {
            get {
                object obj = ResourceManager.GetObject("InjectGreen_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InjectGreen_48 {
            get {
                object obj = ResourceManager.GetObject("InjectGreen_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LinkBreak16 {
            get {
                object obj = ResourceManager.GetObject("LinkBreak16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LinkBreak24 {
            get {
                object obj = ResourceManager.GetObject("LinkBreak24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LinkBreak32 {
            get {
                object obj = ResourceManager.GetObject("LinkBreak32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon lock_open {
            get {
                object obj = ResourceManager.GetObject("lock_open", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NoRed_16 {
            get {
                object obj = ResourceManager.GetObject("NoRed_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NoRed_24 {
            get {
                object obj = ResourceManager.GetObject("NoRed_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NoRed_32 {
            get {
                object obj = ResourceManager.GetObject("NoRed_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NoRed_48 {
            get {
                object obj = ResourceManager.GetObject("NoRed_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ok16 {
            get {
                object obj = ResourceManager.GetObject("ok16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ok24 {
            get {
                object obj = ResourceManager.GetObject("ok24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ok32 {
            get {
                object obj = ResourceManager.GetObject("ok32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ok48 {
            get {
                object obj = ResourceManager.GetObject("ok48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PauseDisabled16 {
            get {
                object obj = ResourceManager.GetObject("PauseDisabled16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PauseDisabled24 {
            get {
                object obj = ResourceManager.GetObject("PauseDisabled24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PauseDisabled32 {
            get {
                object obj = ResourceManager.GetObject("PauseDisabled32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PauseDisabled48 {
            get {
                object obj = ResourceManager.GetObject("PauseDisabled48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcessInfo16 {
            get {
                object obj = ResourceManager.GetObject("ProcessInfo16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcessInfo24 {
            get {
                object obj = ResourceManager.GetObject("ProcessInfo24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcessInfo32 {
            get {
                object obj = ResourceManager.GetObject("ProcessInfo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcessInfo48 {
            get {
                object obj = ResourceManager.GetObject("ProcessInfo48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcessInfo64 {
            get {
                object obj = ResourceManager.GetObject("ProcessInfo64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcessOk16 {
            get {
                object obj = ResourceManager.GetObject("ProcessOk16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcessOk24 {
            get {
                object obj = ResourceManager.GetObject("ProcessOk24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcessOk32 {
            get {
                object obj = ResourceManager.GetObject("ProcessOk32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcessOk48 {
            get {
                object obj = ResourceManager.GetObject("ProcessOk48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcessOk64 {
            get {
                object obj = ResourceManager.GetObject("ProcessOk64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcessWarning16 {
            get {
                object obj = ResourceManager.GetObject("ProcessWarning16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcessWarning24 {
            get {
                object obj = ResourceManager.GetObject("ProcessWarning24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcessWarning32 {
            get {
                object obj = ResourceManager.GetObject("ProcessWarning32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcessWarning48 {
            get {
                object obj = ResourceManager.GetObject("ProcessWarning48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcessWarning64 {
            get {
                object obj = ResourceManager.GetObject("ProcessWarning64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecordDisabled16 {
            get {
                object obj = ResourceManager.GetObject("RecordDisabled16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecordDisabled24 {
            get {
                object obj = ResourceManager.GetObject("RecordDisabled24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecordDisabled32 {
            get {
                object obj = ResourceManager.GetObject("RecordDisabled32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecordDisabled48 {
            get {
                object obj = ResourceManager.GetObject("RecordDisabled48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh_16 {
            get {
                object obj = ResourceManager.GetObject("Refresh_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh_24 {
            get {
                object obj = ResourceManager.GetObject("Refresh_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh_32 {
            get {
                object obj = ResourceManager.GetObject("Refresh_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh16 {
            get {
                object obj = ResourceManager.GetObject("refresh16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh24 {
            get {
                object obj = ResourceManager.GetObject("refresh24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh32 {
            get {
                object obj = ResourceManager.GetObject("refresh32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh48 {
            get {
                object obj = ResourceManager.GetObject("refresh48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap run16 {
            get {
                object obj = ResourceManager.GetObject("run16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap run32 {
            get {
                object obj = ResourceManager.GetObject("run32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap run48 {
            get {
                object obj = ResourceManager.GetObject("run48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap run64 {
            get {
                object obj = ResourceManager.GetObject("run64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Skull16 {
            get {
                object obj = ResourceManager.GetObject("Skull16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Skull24 {
            get {
                object obj = ResourceManager.GetObject("Skull24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Skull32 {
            get {
                object obj = ResourceManager.GetObject("Skull32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon star2 {
            get {
                object obj = ResourceManager.GetObject("star2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon star2_48 {
            get {
                object obj = ResourceManager.GetObject("star2_48", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop_16 {
            get {
                object obj = ResourceManager.GetObject("Stop_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop_24 {
            get {
                object obj = ResourceManager.GetObject("Stop_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop_32 {
            get {
                object obj = ResourceManager.GetObject("Stop_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stop16 {
            get {
                object obj = ResourceManager.GetObject("stop16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stop32 {
            get {
                object obj = ResourceManager.GetObject("stop32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stop48 {
            get {
                object obj = ResourceManager.GetObject("stop48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stop64 {
            get {
                object obj = ResourceManager.GetObject("stop64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StopDisabled16 {
            get {
                object obj = ResourceManager.GetObject("StopDisabled16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StopDisabled24 {
            get {
                object obj = ResourceManager.GetObject("StopDisabled24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StopDisabled32 {
            get {
                object obj = ResourceManager.GetObject("StopDisabled32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StopDisabled48 {
            get {
                object obj = ResourceManager.GetObject("StopDisabled48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Thumbs {
            get {
                object obj = ResourceManager.GetObject("Thumbs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Thunder_16 {
            get {
                object obj = ResourceManager.GetObject("Thunder_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Thunder_16_Icon {
            get {
                object obj = ResourceManager.GetObject("Thunder_16_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Thunder_24 {
            get {
                object obj = ResourceManager.GetObject("Thunder_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Thunder_32 {
            get {
                object obj = ResourceManager.GetObject("Thunder_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Thunder_48 {
            get {
                object obj = ResourceManager.GetObject("Thunder_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Thunder_48_Icon {
            get {
                object obj = ResourceManager.GetObject("Thunder_48_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Thunder_64 {
            get {
                object obj = ResourceManager.GetObject("Thunder_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Unknown16 {
            get {
                object obj = ResourceManager.GetObject("Unknown16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Unknown24 {
            get {
                object obj = ResourceManager.GetObject("Unknown24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Unknown32 {
            get {
                object obj = ResourceManager.GetObject("Unknown32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Unknown48 {
            get {
                object obj = ResourceManager.GetObject("Unknown48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Unknown64 {
            get {
                object obj = ResourceManager.GetObject("Unknown64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wired16 {
            get {
                object obj = ResourceManager.GetObject("Wired16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wired24 {
            get {
                object obj = ResourceManager.GetObject("Wired24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wired32 {
            get {
                object obj = ResourceManager.GetObject("Wired32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wrn16 {
            get {
                object obj = ResourceManager.GetObject("wrn16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wrn24 {
            get {
                object obj = ResourceManager.GetObject("wrn24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wrn32 {
            get {
                object obj = ResourceManager.GetObject("wrn32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wrn48 {
            get {
                object obj = ResourceManager.GetObject("wrn48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zombie16 {
            get {
                object obj = ResourceManager.GetObject("Zombie16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zombie24 {
            get {
                object obj = ResourceManager.GetObject("Zombie24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zombie32 {
            get {
                object obj = ResourceManager.GetObject("Zombie32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zombie48 {
            get {
                object obj = ResourceManager.GetObject("Zombie48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zombie64 {
            get {
                object obj = ResourceManager.GetObject("Zombie64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZoomHS {
            get {
                object obj = ResourceManager.GetObject("ZoomHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
